version: "3"

services:
    react-app:
        image: react-bankapp
        container_name: react-app
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "7001:80"
